services:
  transfers:
    image: arboleda-transfers
    build: 
      context: https://github.com/MarcoVela/arboleda-bank-backend.git
  payments:
    image: arboleda-payments
    build: 
      context: https://github.com/MarcoVela/arboleda-payments.git
  recharges:
    image: arboleda-recharges
    build: 
      context: https://github.com/MarcoVela/arboleda-recharge.git
  nginx:
    image: "nginx:latest"
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      - transfers
      - payments
      - recharges
